apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-deploy
  labels:
    app: web
    kind: frontend
spec:
  template:
    metadata:
      name: web
      labels:
        app: assignment
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx.alpine
  replicas: 5
  selector:
    matchLabels:
      type: frontend
